ex1: ex1.o
	gcc -std=c11 ex1.o -o ex1.out
	./ex1.out

ex2: ex2.o
	gcc -std=c11 ex2.o -o ex2.out
	./ex2.out

ex3: ex3.o
	gcc -std=c11 ex3.o -o ex3.out
	./ex3.out

ex4: ex4.o
	gcc -std=c11 ex4.o -o ex4.out
	./ex4.out

clean:
	rm -rf *.o *.out